# An example Dockerfile for installing Git on Ubuntu
FROM ubuntu:latest
LABEL maintainer="omer@allingeek.com"
RUN apt-get update && apt-get install -y git
ENTRYPOINT ["git"]
RUN This is not working command